version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:29092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  mirror_maker:
    image: confluentinc/cp-kafka:5.3.0
    command: 
      - kafka-mirror-maker
      - --consumer.config
      - /mirror-maker/mirrormaker-consumer.config
      - --producer.config
      - /mirror-maker/mirrormaker-producer.config
      - --whitelist
      - get.event.message.mirrormaker
      - –consumer-property security.protocol=SASL_PLAINTEXT
      - export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf"

    ports:
      - 5555:5555
    environment:
      KAFKA_OPTS: "
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=5555
      "
    volumes:
      - ./mirror-maker:/mirror-maker
      - ./brave-kafka-interceptor/brave-kafka-interceptor-0.5.0.jar:/usr/share/java/kafka/brave-kafka-interceptor-0.5.0.jar

  mirror_maker_jmx:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    ports:
      - 5556:5556
    environment:
      JMX_EXPORTER_HTTP_PORT: 5556
    volumes:
      - ./mirror-maker-jmx/httpserver.yml:/var/lib/docker/overlay2/maker-jmx/merge/jmx-exporter/config/httpserver.yml
    